=== bensonhaley/turtlebreadsite/bakeryitemlist.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT BakeryItemList (SectionName, List)>
<!ELEMENT SectionName (#PCDATA)>
<!ELEMENT List (Item*)>
<!ELEMENT Item (Name, Price, Ingredients)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Ingredients (#PCDATA)>

=== bensonhaley/turtlebreadsite/TurtleBakery.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE BakeryItemList SYSTEM "bakeryitemlist.dtd">
<BakeryItemList>
      <SectionName>Cookies</SectionName>
      <List>
        <Item>
          <Name>Chocolate Chip</Name>
          <Price>&#36;2.49</Price>
          <Ingredients>A, B, C</Ingredients>
        </Item>
        <Item>
          <Name>Oatmeal Raisin</Name>
          <Price>&#36;2.49</Price>
          <Ingredients>A, B, C</Ingredients>
        </Item>
        <Item>
          <Name>Ginger Molasses</Name>
          <Price>&#36;2.49</Price>
          <Ingredients>A, B, C</Ingredients>
        </Item>
        <Item>
          <Name>PB Chocolate Chunk</Name>
          <Price>&#36;2.49</Price>
          <Ingredients>A, B, C</Ingredients>
        </Item>
        <Item>
          <Name>Double Chocolate Chunk</Name>
          <Price>&#36;2.49</Price>
          <Ingredients>A, B, C</Ingredients>
        </Item>
        <Item>
          <Name>Palmier</Name>
          <Price>&#36;2.49</Price>
          <Ingredients>A, B, C</Ingredients>
        </Item>
      </List>
</BakeryItemList>
